// src/pages/Game3/SoalData.js
export const SOAL_POOL = [
    // --- BERPIKIR KOMPUTASIONAL (Computational Thinking) ---
    { id: 1, tanya: "Metode menyelesaikan persoalan dengan menerapkan teknik ilmu komputer disebut?", a: "Berpikir Kritis", b: "Berpikir Komputasional", c: "Berpikir Logis", d: "Berpikir Visual", jawab: "b" },
    { id: 2, tanya: "Teknik memecah masalah besar menjadi bagian-bagian kecil agar lebih mudah dikelola disebut?", a: "Dekomposisi", b: "Pengenalan Pola", c: "Abstraksi", d: "Algoritma", jawab: "a" },
    { id: 3, tanya: "Menyaring informasi yang penting saja dan mengabaikan detail yang tidak relevan disebut?", a: "Dekomposisi", b: "Algoritma", c: "Abstraksi", d: "Searching", jawab: "c" },
    { id: 4, tanya: "Langkah-langkah logis dan berurutan untuk menyelesaikan sebuah masalah disebut?", a: "Abstraksi", b: "Algoritma", c: "Pola", d: "Struktur", jawab: "b" },
    { id: 5, tanya: "Melihat kesamaan atau karakteristik tertentu dalam beberapa masalah disebut?", a: "Dekomposisi", b: "Pengenalan Pola", c: "Abstraksi", d: "Sorting", jawab: "b" },
  
    // --- SISTEM KOMPUTER (Hardware & Software) ---
    { id: 6, tanya: "Komponen fisik komputer yang dapat disentuh dan dilihat disebut?", a: "Software", b: "Brainware", c: "Hardware", d: "Malware", jawab: "c" },
    { id: 7, tanya: "Perangkat lunak yang berfungsi sebagai jembatan antara pengguna dan perangkat keras adalah?", a: "Aplikasi", b: "Sistem Operasi", c: "Browser", d: "Antivirus", jawab: "b" },
    { id: 8, tanya: "Manakah yang termasuk perangkat masukan (Input Device)?", a: "Monitor", b: "Printer", c: "Mouse", d: "Speaker", jawab: "c" },
    { id: 9, tanya: "Perangkat keras yang berfungsi untuk memproses data adalah?", a: "RAM", b: "Harddisk", c: "CPU", d: "Power Supply", jawab: "c" },
    { id: 10, tanya: "Penyimpanan data yang bersifat sementara saat komputer menyala disebut?", a: "ROM", b: "RAM", c: "SSD", d: "Flashdisk", jawab: "b" },
    { id: 11, tanya: "Manakah yang merupakan contoh sistem operasi?", a: "Microsoft Word", b: "Google Chrome", c: "Linux", d: "Adobe Photoshop", jawab: "c" },
    { id: 12, tanya: "Alat yang berfungsi untuk mencetak hasil kerja komputer ke kertas adalah?", a: "Scanner", b: "Plotter", c: "Printer", d: "Monitor", jawab: "c" },
    { id: 13, tanya: "Perangkat yang berfungsi untuk menyimpan data secara permanen adalah?", a: "RAM", b: "Processor", c: "Harddisk", d: "VGA Card", jawab: "c" },
    { id: 14, tanya: "Kepanjangan dari CPU adalah?", a: "Central Processing Unit", b: "Control Processing Unit", c: "Center Program Unit", d: "Core Processing Unit", jawab: "a" },
    { id: 15, tanya: "Satuan terkecil data dalam komputer (0 atau 1) disebut?", a: "Byte", b: "Bit", c: "Mega", d: "Giga", jawab: "b" },
  
    // --- TEKNOLOGI INFORMASI & KOMUNIKASI (Aplikasi Perkantoran) ---
    { id: 16, tanya: "Aplikasi yang digunakan untuk mengolah kata adalah?", a: "MS Excel", b: "MS PowerPoint", c: "MS Word", d: "MS Access", jawab: "c" },
    { id: 17, tanya: "Untuk mengolah data angka dan tabel, kita menggunakan aplikasi?", a: "MS Excel", b: "MS Word", c: "Notepad", d: "Paint", jawab: "a" },
    { id: 18, tanya: "Shortcut pada keyboard untuk menyalin (Copy) teks adalah?", a: "Ctrl + V", b: "Ctrl + X", c: "Ctrl + C", d: "Ctrl + Z", jawab: "c" },
    { id: 19, tanya: "Ekstensi file untuk dokumen Microsoft Word biasanya adalah?", a: ".xlsx", b: ".docx", c: ".pptx", d: ".jpg", jawab: "b" },
    { id: 20, tanya: "Fungsi yang digunakan untuk menjumlahkan data angka di MS Excel adalah?", a: "AVERAGE", b: "MIN", c: "MAX", d: "SUM", jawab: "d" },
    { id: 21, tanya: "Aplikasi yang digunakan untuk membuat presentasi adalah?", a: "MS Word", b: "MS PowerPoint", c: "MS Excel", d: "MS Publisher", jawab: "b" },
    { id: 22, tanya: "Menempelkan hasil kopian (Paste) menggunakan shortcut?", a: "Ctrl + P", b: "Ctrl + S", c: "Ctrl + V", d: "Ctrl + A", jawab: "c" },
    { id: 23, tanya: "Istilah untuk mengirim file dari komputer kita ke internet disebut?", a: "Download", b: "Upload", c: "Browsing", d: "Chatting", jawab: "b" },
    { id: 24, tanya: "Software gratis yang kode programnya boleh dibuka dan dimodifikasi disebut?", a: "Freeware", b: "Shareware", c: "Open Source", d: "Commercial", jawab: "c" },
    { id: 25, tanya: "Untuk mencari informasi di internet, kita menggunakan?", a: "Operating System", b: "Search Engine", c: "Spreadsheet", d: "Database", jawab: "b" },
  
    // --- JARINGAN KOMPUTER & INTERNET ---
    { id: 26, tanya: "Jaringan komputer yang mencakup area satu gedung disebut?", a: "WAN", b: "MAN", c: "LAN", d: "PAN", jawab: "c" },
    { id: 27, tanya: "Kumpulan halaman web yang saling terhubung di internet disebut?", a: "Browser", b: "Website", c: "Server", d: "Provider", jawab: "b" },
    { id: 28, tanya: "Protokol standar untuk bertukar data di internet adalah?", a: "HTTP/HTTPS", b: "HTML", c: "WWW", d: "URL", jawab: "a" },
    { id: 29, tanya: "Alat yang berfungsi menghubungkan dua jaringan atau lebih agar data bisa terkirim adalah?", a: "Monitor", b: "Keyboard", c: "Router", d: "Printer", jawab: "c" },
    { id: 30, tanya: "Kepanjangan dari Wi-Fi adalah?", a: "Wireless Fidelity", b: "Wire Fiber", c: "Wireless Find", d: "Wire Finish", jawab: "a" },
    { id: 31, tanya: "Alamat unik sebuah komputer dalam jaringan disebut?", a: "Home Address", b: "Mac Address", c: "IP Address", d: "Email Address", jawab: "c" },
    { id: 32, tanya: "Internet adalah singkatan dari?", a: "Internal Network", b: "Interconnected Network", c: "International Network", d: "Interactive Network", jawab: "b" },
    { id: 33, tanya: "Topologi jaringan yang berbentuk seperti bintang disebut?", a: "Bus", b: "Ring", c: "Star", d: "Mesh", jawab: "c" },
    { id: 34, tanya: "Kecepatan transfer data internet biasanya dinyatakan dalam satuan?", a: "Meter", b: "Kilogram", c: "bps (bit per second)", d: "Litre", jawab: "c" },
    { id: 35, tanya: "Browser yang merupakan bawaan dari Windows 10/11 adalah?", a: "Safari", b: "Opera", c: "Edge", d: "Chrome", jawab: "c" },
  
    // --- ANALISIS DATA ---
    { id: 36, tanya: "Data yang berupa angka-angka disebut data?", a: "Kualitatif", b: "Kuantitatif", c: "Visual", d: "Audio", jawab: "b" },
    { id: 37, tanya: "Proses mengolah data mentah menjadi informasi yang berguna disebut?", a: "Input Data", b: "Output Data", c: "Analisis Data", d: "Hapus Data", jawab: "c" },
    { id: 38, tanya: "Visualisasi data yang paling tepat untuk melihat tren naik turun adalah?", a: "Pie Chart", b: "Bar Chart", c: "Line Chart", d: "Table", jawab: "c" },
    { id: 39, tanya: "Di MS Excel, simbol untuk memulai sebuah rumus/formula adalah?", a: "+", b: "-", c: "=", d: "*", jawab: "c" },
    { id: 40, tanya: "Mengurutkan data dari terkecil ke terbesar disebut?", a: "Ascending", b: "Descending", c: "Filter", d: "Mix", jawab: "a" },
  
    // --- ALGORITMA & PEMROGRAMAN ---
    { id: 41, tanya: "Bahasa pemrograman visual yang menggunakan blok-blok kode disebut?", a: "Python", b: "Java", c: "Scratch", d: "C++", jawab: "c" },
    { id: 42, tanya: "Simbol belah ketupat pada flowchart digunakan untuk?", a: "Start/End", b: "Proses", c: "Keputusan (Decision)", d: "Input/Output", jawab: "c" },
    { id: 43, tanya: "Perulangan dalam pemrograman sering disebut dengan istilah?", a: "Variable", b: "Looping", c: "Debugging", d: "Input", jawab: "b" },
    { id: 44, tanya: "Tempat menyimpan nilai sementara dalam pemrograman disebut?", a: "Variable", b: "Constant", c: "Loop", d: "Function", jawab: "a" },
    { id: 45, tanya: "Kesalahan dalam kode program disebut?", a: "Virus", b: "Bug", c: "Crack", d: "Lag", jawab: "b" },
  
    // --- DAMPAK SOSIAL INFORMATIKA ---
    { id: 46, tanya: "Tindakan mengintimidasi atau mengejek orang lain di internet disebut?", a: "Cyber Bullying", b: "E-mail", c: "E-commerce", d: "Social Media", jawab: "a" },
    { id: 47, tanya: "Berita bohong yang disebarkan di internet disebut?", a: "Spam", b: "Hoax", c: "Ads", d: "Thread", jawab: "b" },
    { id: 48, tanya: "Etika berkomunikasi di internet disebut?", a: "Etiket", b: "Netiket", c: "Protokol", d: "Aturan", jawab: "b" },
    { id: 49, tanya: "Istilah untuk belanja secara online di internet adalah?", a: "E-banking", b: "E-learning", c: "E-commerce", d: "E-government", jawab: "c" },
    { id: 50, tanya: "Hak eksklusif pencipta atas karya digitalnya dilindungi oleh?", a: "Hak Asasi", b: "Hak Cipta (Copyright)", c: "Hak Milik", d: "Hak Pakai", jawab: "b" },
  
    // ... (DITERUSKAN HINGGA 100 SOAL DENGAN VARIASI SERUPA) ...
    { id: 51, tanya: "Layanan untuk menyimpan file di internet disebut?", a: "Cloud Storage", b: "Local Storage", c: "Hardisk", d: "RAM", jawab: "a" },
    { id: 52, tanya: "Contoh layanan Cloud Storage milik Google adalah?", a: "OneDrive", b: "iCloud", c: "Google Drive", d: "Dropbox", jawab: "c" },
    { id: 53, tanya: "Apa fungsi dari Antivirus?", a: "Mempercepat PC", b: "Mencegah serangan Malware", c: "Mengedit foto", d: "Menjelajah internet", jawab: "b" },
    { id: 54, tanya: "Shortcut Ctrl + S digunakan untuk?", a: "Menghapus", b: "Menyalin", c: "Menyimpan", d: "Mencetak", jawab: "c" },
    { id: 55, tanya: "Kepanjangan dari HTML adalah?", a: "Hypertext Markup Language", b: "Hyperlink Text Language", c: "High Text Markup Language", d: "Home Tool Markup Language", jawab: "a" },
    { id: 56, tanya: "Perangkat keras yang menampilkan visual gambar adalah?", a: "Monitor", b: "CPU", c: "Keyboard", d: "Printer", jawab: "a" },
    { id: 57, tanya: "Kabel jaringan yang menggunakan cahaya untuk transmisi data adalah?", a: "UTP", b: "Coaxial", c: "Fiber Optic", d: "Telepon", jawab: "c" },
    { id: 58, tanya: "Istilah untuk menghidupkan kembali komputer adalah?", a: "Shutdown", b: "Restart", c: "Sleep", d: "Hibernate", jawab: "b" },
    { id: 59, tanya: "Satuan 1 GigaByte sama dengan berapa MegaByte?", a: "100 MB", b: "1000 MB", c: "1024 MB", d: "10000 MB", jawab: "c" },
    { id: 60, tanya: "Aplikasi yang digunakan untuk mengirim surat elektronik adalah?", a: "Browser", b: "Email client", c: "Messenger", d: "Social Media", jawab: "b" },
  
    // --- Lanjutannya disesuaikan dengan topik informatika lainnya (Kriptografi dasar, logika gerbang, sejarah komputer dsb) ---
    { id: 61, tanya: "Siapa ilmuwan yang dijuluki Bapak Komputer?", a: "Bill Gates", b: "Steve Jobs", c: "Charles Babbage", d: "Alan Turing", jawab: "c" },
    { id: 62, tanya: "Teknik menyandikan pesan agar tidak bisa dibaca orang lain disebut?", a: "Kompresi", b: "Enkripsi", c: "Coding", d: "Formatting", jawab: "b" },
    { id: 63, tanya: "Simbol lingkaran pada flowchart biasanya mewakili?", a: "Proses", b: "Konektor/Start-End", c: "Input", d: "Decision", jawab: "b" },
    { id: 64, tanya: "Manakah yang merupakan Input Device khusus untuk bermain game?", a: "Printer", b: "Joystick", c: "Speaker", d: "Monitor", jawab: "b" },
    { id: 65, tanya: "Perangkat keras yang mengubah sinyal digital ke suara adalah?", a: "Monitor", b: "Scanner", c: "Speaker", d: "Plotter", jawab: "c" },
    { id: 66, tanya: "Dalam MS Excel, kolom ditandai dengan?", a: "Angka (1,2,3)", b: "Huruf (A,B,C)", c: "Simbol (*,#,$)", d: "Warna", jawab: "b" },
    { id: 67, tanya: "Dalam MS Excel, baris ditandai dengan?", a: "Huruf (A,B,C)", b: "Angka (1,2,3)", c: "Simbol", d: "Tabel", jawab: "b" },
    { id: 68, tanya: "Fungsi MIN di Excel digunakan untuk mencari?", a: "Nilai rata-rata", b: "Nilai terkecil", c: "Nilai terbesar", d: "Total data", jawab: "b" },
    { id: 69, tanya: "Fungsi MAX di Excel digunakan untuk mencari?", a: "Nilai rata-rata", b: "Nilai terkecil", c: "Nilai terbesar", d: "Total data", jawab: "c" },
    { id: 70, tanya: "Kumpulan data yang disimpan secara terorganisir disebut?", a: "Folder", b: "File", c: "Database", d: "Hardware", jawab: "c" },
    { id: 71, tanya: "Jenis file gambar yang biasanya memiliki latar belakang transparan adalah?", a: "JPG", b: "PNG", c: "BMP", d: "GIF", jawab: "b" },
    { id: 72, tanya: "Sistem bilangan yang hanya menggunakan angka 0 dan 1 disebut?", a: "Desimal", b: "Biner", c: "Oktal", d: "Heksadesimal", jawab: "b" },
    { id: 73, tanya: "Angka biner 10 dalam sistem desimal berarti?", a: "1", b: "2", c: "3", d: "4", jawab: "b" },
    { id: 74, tanya: "Pesan sampah yang masuk ke email tanpa diundang disebut?", a: "Virus", b: "Spam", c: "Hoax", d: "Phishing", jawab: "b" },
    { id: 75, tanya: "Menipiskan ukuran file agar lebih ringan disebut?", a: "Ekstraksi", b: "Kompresi", c: "Enkripsi", d: "Scanning", jawab: "b" },
    { id: 76, tanya: "Manakah yang merupakan contoh browser?", a: "Windows Explorer", b: "Firefox", c: "MS Word", d: "Excel", jawab: "b" },
    { id: 77, tanya: "Kepanjangan dari URL adalah?", a: "Uniform Resource Locator", b: "Universal Resource Line", c: "Unit Resource Link", d: "Uniform Road Link", jawab: "a" },
    { id: 78, tanya: "Media sosial yang fokus pada pencarian kerja adalah?", a: "Instagram", b: "LinkedIn", c: "Snapchat", d: "TikTok", jawab: "b" },
    { id: 79, tanya: "Software yang digunakan untuk browsing disebut?", a: "Operating System", b: "Web Browser", c: "Utility", d: "Application", jawab: "b" },
    { id: 80, tanya: "Salah satu contoh hardware output adalah?", a: "Keyboard", b: "Monitor", c: "Mouse", d: "Scanner", jawab: "b" },
    { id: 81, tanya: "Bluetooth merupakan teknologi nirkabel jarak?", a: "Dekat", b: "Jauh", c: "Sangat Jauh", d: "Antar Benua", jawab: "a" },
    { id: 82, tanya: "Tanda pagar (#) dalam media sosial disebut?", a: "Link", b: "Hashtag", c: "Tag", d: "Mention", jawab: "b" },
    { id: 83, tanya: "Istilah 'Log In' artinya?", a: "Keluar sistem", b: "Masuk ke sistem", c: "Menghapus akun", d: "Membuat akun", jawab: "b" },
    { id: 84, tanya: "Untuk membatalkan perintah terakhir (Undo) menggunakan?", a: "Ctrl + Y", b: "Ctrl + Z", c: "Ctrl + A", d: "Ctrl + S", jawab: "b" },
    { id: 85, tanya: "Nama lain dari layar komputer adalah?", a: "CPU", b: "Keyboard", c: "Monitor", d: "Casing", jawab: "c" },
    { id: 86, tanya: "Mouse pertama kali dibuat dari bahan?", a: "Besi", b: "Kayu", c: "Plastik", d: "Kaca", jawab: "b" },
    { id: 87, tanya: "Siapa pendiri Facebook?", a: "Mark Zuckerberg", b: "Elon Musk", c: "Steve Jobs", d: "Jeff Bezos", jawab: "a" },
    { id: 88, tanya: "Alat yang memindai gambar/dokumen menjadi file digital adalah?", a: "Printer", b: "Scanner", c: "Speaker", d: "Monitor", jawab: "b" },
    { id: 89, tanya: "Manakah yang merupakan bahasa pemrograman paling populer untuk pemula?", a: "Assembly", b: "Python", c: "C", d: "COBOL", jawab: "b" },
    { id: 90, tanya: "Dalam Scratch, kita menyusun blok kode di area?", a: "Stage", b: "Sprite list", c: "Scripts area", d: "Costume", jawab: "c" },
    { id: 91, tanya: "Karakter atau objek dalam Scratch disebut?", a: "Block", b: "Sprite", c: "Costume", d: "Backdrop", jawab: "b" },
    { id: 92, tanya: "Tombol Bendera Hijau di Scratch berfungsi untuk?", a: "Berhenti", b: "Memulai program", c: "Menghapus", d: "Menyimpan", jawab: "b" },
    { id: 93, tanya: "Jenis memori yang hanya bisa dibaca dan tidak bisa diubah datanya?", a: "RAM", b: "ROM", c: "Hardisk", d: "SSD", jawab: "b" },
    { id: 94, tanya: "Alat input yang digunakan untuk menggambar langsung di komputer?", a: "Keyboard", b: "Pen Tablet", c: "Scanner", d: "Printer", jawab: "b" },
    { id: 95, tanya: "Domain .gov digunakan untuk situs milik?", a: "Pendidikan", b: "Pemerintah", c: "Organisasi", d: "Perusahaan", jawab: "b" },
    { id: 96, tanya: "Domain .edu atau .ac.id digunakan untuk?", a: "Bisnis", b: "Pemerintah", c: "Pendidikan", d: "Sosial", jawab: "c" },
    { id: 97, tanya: "Kepanjangan dari LCD adalah?", a: "Liquid Crystal Display", b: "Light Crystal Display", c: "Liquid Color Display", d: "Light Color Display", jawab: "a" },
    { id: 98, tanya: "Manakah yang bukan merupakan alat komunikasi modern?", a: "Smartphone", b: "E-mail", c: "Kentongan", d: "Video Call", jawab: "c" },
    { id: 99, tanya: "Kepanjangan dari USB adalah?", a: "Universal Serial Bus", b: "Unit Serial Bus", c: "Universal Sound Bus", d: "Unit Sound Bus", jawab: "a" },
    { id: 100, tanya: "Informasi yang ditampilkan oleh komputer disebut?", a: "Input", b: "Output", c: "Process", d: "Storage", jawab: "b" }
  ];